package workerScreenController;
import javafx.scene.image.Image;

import java.io.IOException;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import client.ClientController;
import enums.Commands;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import logic.LoginDetail;
import logic.ManagerRequestDetail;
import logic.Message;
import workerScreenController.WorkerScreenController;


public class ParkManagerScreenController extends WorkerScreenController{
	
	@FXML
	private TextField ParkCapacityT;
	@FXML
	private TextField OnlineBookingCapacityT;
	@FXML
	private TextField AverageParkStayTimeT;
	@FXML
	private ImageView parkImgT;
    @FXML
    private Button parkDashboard;

    @FXML
    private Button visitorStatisticReport;

    @FXML
    private Button parkAvailabilityReport;

    @FXML
    private Button logout;

	@FXML
	private Text parkNameT;
	@FXML
	private Text visitorAmountT;
	
	@FXML
	private Text MessageT;
	
	private String parkName;
	
	private String getParkCapacity() {
		return ParkCapacityT.getText();
	}
	private String getOnlineBookingCapacity() {
		return OnlineBookingCapacityT.getText();
	}
	private String getAverageParkStayTime() {
		return AverageParkStayTimeT.getText();
	}
	
	public void refreshBtn(ActionEvent event) throws Exception{
		//setVisitorAmount();
		visitorAmountT.setText(getCurrentOccupancy());
	}
	
	/**
	 * Handles the action event for setting the park capacity.
	 * Retrieves the value for park capacity and sends a request to change it to the server.
	 * @param event The action event generated by clicking the set park capacity button.
	 * @throws Exception Throws Exception if an error occurs during execution.
	 */
	public void setParkCapacityBtn(ActionEvent event) throws Exception
	{
		MessageT.setVisible(true);
		String valueTo = getParkCapacity();
		if(valueTo == "") {
			MessageT.setText("Please Enter A value First.");
		}
		else if(valueTo.length() > 7 || Integer.valueOf(valueTo) < 0)
			MessageT.setText("Invalid Value, Try Again.");
		else {
		ManagerRequestDetail managerRequestDetail = new ManagerRequestDetail(parkName,"Set Park Capacity of ",valueTo);
		Message addmsg = new Message(managerRequestDetail,Commands.AddManagerRequestDetail);
		ClientController.client.sendToServer(addmsg);
		MessageT.setText("Message Sent To Department Manager For Confirmation.");
		ParkCapacityT.clear();
		}
		
	}
	
	/**
	 * Handles the action event for setting the online booking capacity.
	 * Retrieves the value for online booking capacity and sends a request to change it to the server.
	 * @param event The action event generated by clicking the set online booking capacity button.
	 * @throws Exception Throws Exception if an error occurs during execution.
	 */
	public void setOnlineBookingCapacityBtn(ActionEvent event) throws Exception
	{
		MessageT.setVisible(true);
		String valueTo = getOnlineBookingCapacity();
		if(valueTo == "") {
			MessageT.setText("Please Enter A value First.");
		}
		else if(valueTo.length() > 7 || Integer.valueOf(valueTo) < 0)
			MessageT.setText("Invalid Value, Try Again.");
		else {
		ManagerRequestDetail managerRequestDetail = new ManagerRequestDetail(parkName,"Set Online Booking Capacity of ",valueTo);
		Message addmsg = new Message(managerRequestDetail,Commands.AddManagerRequestDetail);
		ClientController.client.sendToServer(addmsg);
		MessageT.setText("Message Sent To Department Manager For Confirmation.");
		OnlineBookingCapacityT.clear();
		}
	}
	
	/**
	 * Handles the action event for setting the average park stay time.
	 * Retrieves the value for average park stay time and sends a request to change it to the server.
	 * @param event The action event generated by clicking the set average park stay time button.
	 * @throws Exception Throws Exception if an error occurs during execution.
	 */
	public void setAverageParkStayTimeBtn(ActionEvent event) throws Exception
	{
		MessageT.setVisible(true);
		String valueTo = getAverageParkStayTime();
		if(valueTo == "") {
			MessageT.setText("Please Enter A value First.");
		}
		else if(valueTo.length() > 7 || Integer.valueOf(valueTo) < 0)
			MessageT.setText("Invalid Value, Try Again.");
		else {
		ManagerRequestDetail managerRequestDetail = new ManagerRequestDetail(parkName,"Set Park Stay Time of ",valueTo);
		Message addmsg = new Message(managerRequestDetail,Commands.AddManagerRequestDetail);
		ClientController.client.sendToServer(addmsg);
		
		MessageT.setText("Message Sent To Department Manager For Confirmation.");
		AverageParkStayTimeT.clear();
		}
	}
	
	/**
	 * Initializes and displays the Park Manager screen.
	 * @param primaryStage The primary stage to set the scene.
	 * @throws Exception Throws Exception if an error occurs during execution.
	 */
	public void start(Stage primaryStage) throws Exception {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/gui/WorkerScreens/ParkManagerScreen.fxml"));
    	loader.setController(this); // Set the controller
    	Parent root = loader.load();
    	Scene scene = new Scene(root);
    	primaryStage.setTitle("GoNature Dashboard");
    	primaryStage.setScene(scene);
    	RemoveTopBar(primaryStage,root);
    	primaryStage.show();
    	setPark(ClientController.client.workerController.getWorkerDetail().getParkName());
    	//welcomebackt.setText("Welcome Back " + ClientController.client.workerController.getWorkerDetail().getName());
    	//setVisitorAmount();
    	visitorAmountT.setText(getCurrentOccupancy());

	}
	
	/**
	 * Sets the park name and related UI elements.
	 * @param parkName The name of the park to set.
	 */
	private void setPark(String parkName) {
		this.parkName = parkName;
		//getcapacity();
		System.out.println(parkName + "this is the park u are ahrai alav");
		parkNameT.setText(parkName);
		String imgS = "/images/" + parkName + ".jpeg";
		Image img = new Image(imgS);
		parkImgT.setImage(img);
	}
	
	/**
	 * Sets the visitor amount for the park.
	 * @throws Exception Throws Exception if an error occurs during execution.
	 */
	private void setVisitorAmount() throws Exception 
	{
		Message msg = new Message(parkName,Commands.getVisitorAmountInPark);
		ClientController.client.sendToServer(msg);
		boolean awaitResponse = false;
        // wait for response
		while (!awaitResponse) {
			try {
				Thread.sleep(100);
				awaitResponse = ClientController.client.workerController.isGotResponse();
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
		ClientController.client.workerController.setGotResponse(false);
		int VistorAmount =  ClientController.client.workerController.getVistorAmount();
		visitorAmountT.setText(Integer.toString(VistorAmount));
	}

	
	
	
	
	
	
}
